export const dummy = [
  {
    id: "1",
    title: "Morning Gym",
    description: "Chest & Triceps workout",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438",
    category: "Health",
    priority: "High",
    status: "Todo",
    dueDate: "2026-07-24",
    dueTime: "07:00 AM",
    createdAt: "2026-07-23",
    favorite: true,
    location: "Gold Gym",
    tags: ["gym", "fitness"],
    subTasks: [
      {
        id: "1",
        title: "Warmup",
        completed: true,
      },
      {
        id: "2",
        title: "Bench Press",
        completed: false,
      },
    ],
  },

  {
    id: "2",
    title: "Buy Groceries",
    description: "Milk, Chicken, Eggs, Fruits",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e",
    category: "Shopping",
    priority: "Medium",
    status: "Todo",
    dueDate: "2026-07-24",
    dueTime: "06:00 PM",
    createdAt: "2026-07-23",
    favorite: false,
    location: "DMart",
    tags: ["shopping"],
    subTasks: [],
  },

  {
    id: "3",
    title: "Doctor Appointment",
    description: "Dental checkup",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef",
    category: "Health",
    priority: "High",
    status: "In Progress",
    dueDate: "2026-07-25",
    dueTime: "10:30 AM",
    createdAt: "2026-07-22",
    favorite: true,
    location: "Apollo Hospital",
    tags: ["doctor"],
    subTasks: [],
  },
  {
    id: "4",
    title: "Morning Gym",
    description: "Chest & Triceps workout",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438",
    category: "Health",
    priority: "High",
    status: "Todo",
    dueDate: "2026-07-24",
    dueTime: "07:00 AM",
    createdAt: "2026-07-23",
    favorite: true,
    location: "Gold Gym",
    tags: ["gym", "fitness"],
    subTasks: [
      {
        id: "1",
        title: "Warmup",
        completed: true,
      },
      {
        id: "2",
        title: "Bench Press",
        completed: false,
      },
    ],
  },

  {
    id: "5",
    title: "Buy Groceries",
    description: "Milk, Chicken, Eggs, Fruits",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e",
    category: "Shopping",
    priority: "Medium",
    status: "Todo",
    dueDate: "2026-07-24",
    dueTime: "06:00 PM",
    createdAt: "2026-07-23",
    favorite: false,
    location: "DMart",
    tags: ["shopping"],
    subTasks: [],
  },

  {
    id: "",
    title: "Doctor Appointment",
    description: "Dental checkup",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef",
    category: "Health",
    priority: "High",
    status: "In Progress",
    dueDate: "2026-07-25",
    dueTime: "10:30 AM",
    createdAt: "2026-07-22",
    favorite: true,
    location: "Apollo Hospital",
    tags: ["doctor"],
    subTasks: [],
  },
];
